config/routes.rb
Rails.application.routes.draw do
  resources :vocabularies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
    
  self.table_name = "Vocabulary"
  self.primary_key = "vocabulary_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  before_action :set_vocabulary, only: [:show, :edit, :update, :destroy]

  # GET /vocabularies
  # GET /vocabularies.json
  def index
    @vocabularies = Vocabulary.all
  end

  # GET /vocabularies/1
  # GET /vocabularies/1.json
  def show
  end

  # GET /vocabularies/new
  def new
    @vocabulary = Vocabulary.new
  end

  # GET /vocabularies/1/edit
  def edit
  end

  # POST /vocabularies
  # POST /vocabularies.json
  def create
    @vocabulary = Vocabulary.new(vocabulary_params)

    respond_to do |format|
      if @vocabulary.save
        format.html { redirect_to @vocabulary, notice: 'Vocabulary was successfully created.' }
        format.json { render :show, status: :created, location: @vocabulary }
      else
        format.html { render :new }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabularies/1
  # PATCH/PUT /vocabularies/1.json
  def update
    respond_to do |format|
      if @vocabulary.update(vocabulary_params)
        format.html { redirect_to @vocabulary, notice: 'Vocabulary was successfully updated.' }
        format.json { render :show, status: :ok, location: @vocabulary }
      else
        format.html { render :edit }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabularies/1
  # DELETE /vocabularies/1.json
  def destroy
    @vocabulary.destroy
    respond_to do |format|
      format.html { redirect_to vocabularies_url, notice: 'Vocabulary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulary
      @vocabulary = Vocabulary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocabulary_params
      params.fetch(:vocabulary, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aeolus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vocabularies/_form.html.erb
<%= form_with(model: vocabulary, local: true) do |form| %>
  <% if vocabulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vocabulary.errors.count, "error") %> prohibited this vocabulary from being saved:</h2>

      <ul>
      <% vocabulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vocabularies/edit.html.erb
<h1>Editing Vocabulary</h1>

<%= render 'form', vocabulary: @vocabulary %>

<%= link_to 'Show', @vocabulary %> |
<%= link_to 'Back', vocabularies_path %>

app/views/vocabularies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vocabularies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vocabularies.each do |vocabulary| %>
      <tr>
        <td><%= link_to 'Show', vocabulary %></td>
        <td><%= link_to 'Edit', edit_vocabulary_path(vocabulary) %></td>
        <td><%= link_to 'Destroy', vocabulary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vocabulary', new_vocabulary_path %>

app/views/vocabularies/new.html.erb
<h1>New Vocabulary</h1>

<%= render 'form', vocabulary: @vocabulary %>

<%= link_to 'Back', vocabularies_path %>

app/views/vocabularies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vocabulary_path(@vocabulary) %> |
<%= link_to 'Back', vocabularies_path %>